### ISSUE TITLE
OS X Support.

### ISSUE THREAD

**Issue by dharhas** [conda-forge/vtk-feedstock#10]
Hi All,

Is there anything particular blocking building an OS X package. I tried to look through the original pull requests but had trouble working out why exactly the OS X build was removed.
- d

**Comment by jakirkham** [comment]
IIRC it was a build time issue. Though @Korijn can probably say more.

**Comment by jakirkham** [comment]
We have been discussing doing manual builds and uploads for some of these longer running builds. There is a CFEP ( conda-forge enhancement proposal ) in the works on this topic. Your feedback would definitely be welcome there. Please see PR ( https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/5 ) for details.

**Comment by Korijn** [comment]
Yeah, build timeouts. OS X and Iinux build times are _just_ over the limits imposed by the free plans offered by the CI services. The build scripts should already work though (they don't error out and reach the stage where conda-build is packaging up the build).

**Comment by Korijn** [comment]
Also see #6

**Comment by jakirkham** [comment]
Ok, so I know we said stick to 1 core on Travis CI before because that's what they give us. We could try to be more aggressive with that setting and do 2. Maybe it completes in time without crashing? Not the best solution, but it is *a* way to try and address this.

**Comment by Korijn** [comment]
I think ninja already does this currently.

**Comment by astrofrog** [comment]
I'd love to see OSX packages too. Just out of curiosity, has anyone asked the Travis folks if they are willing to increase the build time limit for the OSX builds?

**Comment by ocefpaf** [comment]
> Just out of curiosity, has anyone asked the Travis folks if they are willing to increase the build time limit for the OSX builds for conda-forge?

I did and they offered some extra time in exchange of reducing our concurrence. The extra time was not going to be enough and the concurrence is more important due to the high number of package that we build. So we did not accepted their offer.

**Comment by astrofrog** [comment]
@ocefpaf - ok, that makes sense - I wonder if they would accept to do that on a package by package basis - that is, specifically for ``vtk-feedstock`` we could trade concurrence for extra time?

**Comment by ocefpaf** [comment]
We can try to ask again but I would put my efforts on https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/5 instead.

**Comment by Korijn** [comment]
FYI I also asked them, to no avail.

**Comment by thomasaarholt** [comment]
Are there any alternatives for installing a built version of VTK on mac? I have yet to find an easy way of getting it installed.

**Comment by dfroger** [comment]
On anaconda.org, there are other channels than `conda-forge` which provide OSX build:
    https://anaconda.org/search?q=platform%3Aosx-64+vtk

**Comment by thomasaarholt** [comment]
@dfroger Of course. You're entirely right, and it seems to be installing happily now. Thanks for the help.

**Comment by jakirkham** [comment]
FWIW the last time we looked at this Travis CI gave us 1 core per build. They have since given us 2 cores per build. Maybe worth trying a parallel build to see how it goes.

**Comment by Korijn** [comment]
There was a PR (https://github.com/conda-forge/vtk-feedstock/issues/10) working on this but it doesn't look like it will ever build within Travis CI build timeout limits.

**Comment by thomasaarholt** [comment]
fyi @Korijn you just linked to this issue, rather than another PR

**Comment by christianbrodbeck** [comment]
Bad news for projects depending on VTK...

**Comment by Korijn** [comment]
If anyone knows of a way to speed up the OS X build even more, they are welcome to open a PR!

Also, I heard it is possible for @conda-forge/core to upload builds manually...

**Comment by christianbrodbeck** [comment]
Manual upload sounds like it might be a solution? Do you know what that would entail?

**Comment by Korijn** [comment]
I'm actually having the same issue with wxpython-feedstock and am hoping someone from @conda-forge/core can enlighten us!

**Comment by jakirkham** [comment]
Should we reopen then or do you want that in a new issue, @Korijn?

**Comment by Korijn** [comment]
Perhaps a new issue would be better to avoid clutter...
