### ISSUE TITLE
vtk9: conda related cmake issues

### ISSUE THREAD

**Issue by looooo** [conda-forge/vtk-feedstock#142]
- bad paths in ${PREFIX}/lib/cmake/vtk-9.0/VTK*
```
/home/conda/feedstock_root/build_artifacts/vtk_.*_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/home/conda  
/feedstock_root/build_artifacts/vtk_.*_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib.*
```

- sysroot paths somehow added via find_package(VTK)  which lead to errors:
```
ninja: error: '/opt/conda/conda-bld/smesh_1597229682199/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/librt.so', needed by 'libSMDS.so.8.3.0.4', missing and no known rule to make it
```

encountered in:
https://github.com/conda-forge/smesh-feedstock/pull/34

**Comment by looooo** [comment]
Some of these issues could be avoided by linking to libraries using the PRIVATE keyword:
https://cmake.org/cmake/help/latest/command/target_link_libraries.html#libraries-for-a-target-and-or-its-dependents

**Comment by Tobias-Fischer** [comment]
Fixed by https://github.com/conda-forge/vtk-feedstock/commit/8fcd00327e3e312b4c62c56b5b1f71d41784acf3
