### ISSUE TITLE
Rebuild with HDF5 1.12.0 or 1.12.1

### ISSUE THREAD

**Issue by MarDiehl** [conda-forge/vtk-feedstock#200]
Would it be possible to build the package with the most recent HDF5 version, which is 1.12.1?

Note that minor HDF5 versions are usually incompatible, i.e. it is unlikely that a build of VTK that supports the current 1.10.x and 1.12.x is possible

**Comment by MarDiehl** [comment]
I encountered similar issues as described in https://github.com/conda-forge/vtk-feedstock/issues/198 when using HDF5 1.12 and h5py.

**Comment by matthiasdiener** [comment]
Done in #222.
