### ISSUE TITLE
vtk broken?

### ISSUE THREAD

**Issue by christianbrodbeck** [conda-forge/vtk-feedstock#21]
I'm trying to write a [recipe](https://github.com/conda-forge/staged-recipes/pull/2201) that depends on mayavi and hence vtk, and for Linux it ends with the traceback below. This looks like something is missing after the vtk install through conda-forge? Or is there a workaround for this, in which case maybe vtk could raise a better error message? 

```
Traceback (most recent call last):
  File "/staged-recipes/build_artefacts/pysurfer_1485201053033/_t_env/bin/pysurfer", line 9, in <module>
    from surfer._commandline import parser
  File "/staged-recipes/build_artefacts/pysurfer_1485201053033/_t_env/lib/python2.7/site-packages/surfer/__init__.py", line 1, in <module>
    from .viz import Brain, TimeViewer  # noqa
  File "/staged-recipes/build_artefacts/pysurfer_1485201053033/_t_env/lib/python2.7/site-packages/surfer/viz.py", line 13, in <module>
    from mayavi import mlab
  File "/staged-recipes/build_artefacts/pysurfer_1485201053033/_t_env/lib/python2.7/site-packages/mayavi/mlab.py", line 27, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/staged-recipes/build_artefacts/pysurfer_1485201053033/_t_env/lib/python2.7/site-packages/mayavi/tools/camera.py", line 25, in <module>
    from .engine_manager import get_engine
  File "/staged-recipes/build_artefacts/pysurfer_1485201053033/_t_env/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/staged-recipes/build_artefacts/pysurfer_1485201053033/_t_env/lib/python2.7/site-packages/mayavi/core/engine.py", line 12, in <module>
    import vtk
  File "/staged-recipes/build_artefacts/pysurfer_1485201053033/_t_env/lib/python2.7/site-packages/vtk/__init__.py", line 100, in <module>
    from .vtkRenderingOpenGL import *
  File "/staged-recipes/build_artefacts/pysurfer_1485201053033/_t_env/lib/python2.7/site-packages/vtk/vtkRenderingOpenGL.py", line 9, in <module>
    from vtkRenderingOpenGLPython import *
ImportError: No module named vtkRenderingOpenGLPython
```

**Comment by Korijn** [comment]
I don't think Mayavi is on conda-forge yet so I don't think the one in defaults could work with this version of VTK.

**Comment by christianbrodbeck** [comment]
The reason I assumed it was a general `vtk` problem is that the error happens during a bare `import vtk` statement. Could this be due to mayavi?

Mayavi on defaults does misspecify its `vtk` dependency and I've opened an issue for that (https://github.com/ContinuumIO/anaconda-issues/issues/1365)

However the output before the exception contains the following lines, suggesting that mayavi is coming from `conda-forge` (I think it was added very recently though):

```
The following packages will be downloaded:

...
    mayavi-4.5.0               |      np111py27_1        12.8 MB  conda-forge
...

```

The Mayavi conda-forge recipe (https://github.com/conda-forge/mayavi-feedstock) explicitly requires `vtk  ==7.1.0` (https://github.com/conda-forge/mayavi-feedstock/blob/master/recipe/meta.yaml#L31)

**Comment by Korijn** [comment]
You are right.

I'm confused though; the mayavi-feedstock CI is passing on all platforms: https://github.com/conda-forge/mayavi-feedstock/pull/2

You'd think this error would occur there as well, hm?

**Comment by christianbrodbeck** [comment]
Might the relevant difference be that PySurfer imports `mlab` from mayavi, which I don't think the mayavi feedstock test does? Unfortunately I don't have access to Linux to test this with vtk 7.

**Comment by Korijn** [comment]
Actually, I think VTK is being built with vtkRenderingOpenGL2 instead of 1, and Mayavi isn't compatible with that.

**Comment by dfroger** [comment]
> requires vtk ==7.1.0

There is a discussion about that: https://github.com/conda-forge/mayavi-feedstock/issues/1

**Comment by dfroger** [comment]
> mayavi-feedstock CI is passing on all platforms: conda-forge/mayavi-feedstock#2

I just merged this PR, so mayavi should br available on Linux and Windows (i a few minutes), but not OSX (https://github.com/conda-forge/mayavi-feedstock/issues/3)

**Comment by dfroger** [comment]
> ImportError: No module named vtkRenderingOpenGLPython

I'll try to reproduce this

**Comment by dfroger** [comment]
Here https://circleci.com/gh/conda-forge/staged-recipes/12483?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link mayavi is installed from default (don't know the reason why).

On my Linux machine, this install mayavi from conda-forge:
    conda create -n sufer mayavi python=2.7 imageio matplotlib mayavi nibabel numpy scipy

and this works:
    source activate surfer
    python -c 'import vtk'
    python -c 'import mayavi'
    mayavi --help

**Comment by dfroger** [comment]
I think `py-surfer` recipe need to add `libXt-devel` and `mesa-libGLU-devel` to its `yum_requirements.txt`, like [the mayavi one](https://github.com/conda-forge/mayavi-feedstock/blob/1d2e2f70218283a5ac39c8e0c69065ad570c868a/recipe/yum_requirements.txt)

**Comment by dfroger** [comment]
Is it possible to modify VTK recipe so that it is checked? (post install script, or something like this)

**Comment by Korijn** [comment]
I think that is already the case?

```yaml
test:
  imports:
    - vtk
    - vtk.vtkChartsCore
    - vtk.vtkCommonCore
    - vtk.vtkFiltersCore
    - vtk.vtkFiltersGeneric
    - vtk.vtkGeovisCore
    - vtk.vtkFiltersHybrid
    - vtk.vtkIOCore
    - vtk.vtkImagingCore
    - vtk.vtkInfovisCore
    - vtk.vtkRenderingCore
    - vtk.vtkViewsCore
    - vtk.vtkRenderingVolume
    - vtk.vtkInteractionWidgets
```

**Comment by christianbrodbeck** [comment]
> Here https://circleci.com/gh/conda-forge/staged-recipes/12483?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link mayavi is installed from default (don't know the reason why).

Yes strange, this is still the same in [the latest build](https://circleci.com/gh/conda-forge/staged-recipes/12816?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), for the build it's pulling `mayavi` from `defaults`, but for the test it's pulling from `conda-forge`. The only difference in the requirements is that build also has `setuptools`, that can hardly be the reason? A difference in channel priorities?

**Comment by Korijn** [comment]
Care to share your `conda config --get` and `conda info`?

The latest few versions of conda and conda-build are notoriously buggy by the way, we've been having weird hiccups for the last two weeks for all sorts of stuff...

**Comment by christianbrodbeck** [comment]
@Korijn I was referring to the build on circleci (linked), not my machine.

**Comment by christianbrodbeck** [comment]
Closing, since updating `yum_requirements` solved my issue. Thanks!

**Comment by dfroger** [comment]
@christianbrodbeck thanks, I think we should find a way to make it more explicit, document it, or check it before the error occurs to provide to explict warning. Without a doubt, the error will reappear for other users...

**Comment by Korijn** [comment]
It was surprising for me to see that it raised an ImportError at the python level and not at the dll/so level...

**Comment by christianbrodbeck** [comment]
Could a comment be added to the VTK feedstock readme? Something like "Projects that depend on VTK should add a `yum_requirements.txt` file like `vtk-feedstock/recipe/yum_requirements.txt`. Failure to do so can result in an `ImportError: No module named vtkRenderingOpenGLPython`."? That would show up when searching for "vtkRenderingOpenGLPython".

> It was surprising for me to see that it raised an ImportError at the python level and not at the dll/so level

Yes that was confusing for me too, maybe VTK could be modified to raise a more meaningful error? I am not familiar with the [VTK source](https://gitlab.kitware.com/vtk/vtk) though... searching for "vtkRenderingOpenGLPython" does not even yield any results...

**Comment by dfroger** [comment]
> Could a comment be added to the VTK feedstock readme?

As README are generated by conda-smithy, is it ok to modify them?

**Comment by christianbrodbeck** [comment]
Right... is there any way to add notes to a feedstock except for comments in the `meta.yaml` which seem to be discouraged?

**Comment by Korijn** [comment]
@christianbrodbeck VTK autogenerates the Python wrappers with lots of CMake magic, see: https://github.com/Kitware/VTK/blob/0937c8a6be8a10b95828c31b289cd1cecce78432/CMake/vtkPythonWrapping.cmake

**Comment by jakirkham** [comment]
Comments in the recipe are ok. We just try to remove boilerplate comments that come from copying and tweaking the `example` at `staged-recipes`.

Also it is possible to add a README to the `recipe` directory. Here's an [example]( https://github.com/conda-forge/vs2008_express_vc_python_patch-feedstock/tree/master/recipe ) (albeit not the prettiest one).

**Comment by kazemSafari** [comment]
Hi i'm trying to install "mayavi". So i installed all the prerequisite packages including vtk. But after type enter "pip install mayavi" into my ubuntu 16.04 shell, i get a similar error:
"from vtkOpenGLKitPython import *
ModuleNotFoundError: No module named 'vtkOpenGLKitPython'"

How can i fix this error. I did not get your solution "christianbrodbeck"?

**Comment by thecortex** [comment]
ImportError: No module named 'vtkOpenGLKitPython'

**Comment by christianbrodbeck** [comment]
@kazemSafari sorry I missed your comment, this issue is about conda-forge recipes, not local install issues. It looks like your VTK install failed somehow?
