### ISSUE TITLE
osmesa/mesalib no longer available

### ISSUE THREAD

**Issue by gdevenyi** [conda-forge/vtk-feedstock#223]
As of https://github.com/conda-forge/vtk-feedstock/pull/127 mesalib was disabled.

This makes vtk from conda-forge useless on HPC systems with no X/opengl hardware.

**Comment by basnijholt** [comment]
There are two attempts to reenable it:
* https://github.com/conda-forge/vtk-feedstock/pull/153
* https://github.com/conda-forge/vtk-feedstock/pull/224

**Comment by matthiasdiener** [comment]
This should be fixed by #225.
