### ISSUE TITLE
XDMF I/O python bindings?

### ISSUE THREAD

**Issue by truenicoco** [conda-forge/vtk-feedstock#28]
It would be nice to enable XDMF reader and writer classes. According to David E DeMarle from kitware (from vtk-users mailing list):

> xdmf2 reader is on by default in vtk so it should be present in most distributions. Xdmf3 is less so.  It's added boost dependency makes it off by default. Both are wrappable.

**Comment by Korijn** [comment]
feel free to open a PR

**Comment by truenicoco** [comment]
Although unfamiliar with conda recipes, I gave it a quick loop and couldn't find where XDMF support was disabled in compiling parameters. If I end up building VTK (which I never did yet) and find out a solution, I'll be pleased to open a PR.

**Comment by Korijn** [comment]
Unfortunately it doesn't look like anyone else is willing to chip in, so unless you dive into the subject, it's probably not happening anytime soon.
