### ISSUE TITLE
qt6-main version of vtk, how to place in conda-forge

### ISSUE THREAD

**Issue by lasergyro** [conda-forge/vtk-feedstock#299]
### Comment:

I'm trying to use vtk with qt6 in the same python interpreter [feedstock here](https://github.com/conda-forge/vtk-feedstock/compare/main...lasergyro:vtk-feedstock:main).
It runs the manual example in my local machine, it might fail in other systems but I would need to put it in CI for that.
Assuming it works, what would be the best option to integrate this in conda? Two variants of vtk?

**Comment by Tobias-Fischer** [comment]
See https://github.com/conda-forge/qt-main-feedstock/issues/49

**Comment by Tobias-Fischer** [comment]
Should be done in #328
