### ISSUE TITLE
VTK with openmp and mpi

### ISSUE THREAD

**Issue by marcelotrevisani** [conda-forge/vtk-feedstock#38]
Hello folks, is there any reason why the vtk package is not compiled with the openmp and mpi flag?

Because if I compile it with these flags some parts of the vtk will take advantage of the parallelism which openmp and mpi provides as well.

Is it possible to add that? Or will it be better if we add another build with these parameters?

**Comment by Korijn** [comment]
Feel free to open a PR.

**Comment by marcelotrevisani** [comment]
Related to #44

**Comment by banesullivan** [comment]
Was MPI support ever added?
