### ISSUE TITLE
align to conda-forge pinnings

### ISSUE THREAD

**Issue by looooo** [conda-forge/vtk-feedstock#62]
conda-forge pinnings updated hdf5. Please update this recipe to use the same version.

**Comment by jakirkham** [comment]
So PR ( https://github.com/conda-forge/vtk-feedstock/pull/56 ) is refreshed. It's lagging a bit on the `hdf5` pinning (would be `1.10.1` instead of `1.10.2`), but so is the whole stack, which is part of the reason it will lag (`libnetcdf` needs `1.10.1` ATM). The rest are current.

**Comment by looooo** [comment]
ah good idea. I didn't know manual pinning overwrites the conda-forge-pinning.

**Comment by jakirkham** [comment]
Yeah, should be careful with it as things can go stale or get unmaintainable that way, but for now that seemed like the path of least resistance for `vtk` and its use of `hdf5`. There's a bunch of other tricks one can use. This [doc page]( https://conda.io/docs/user-guide/tasks/build-packages/variants.html ) is probably the most useful in this regard.
