### ISSUE TITLE
Build with xdmf

### ISSUE THREAD

**Issue by AntoineD** [conda-forge/vtk-feedstock#66]
Hello,

would it be possible to build vtk with xdmf support?

Cheers,
Antoine.

**Comment by AntoineD** [comment]
Hello,

Is anyone looking at the issues?

Cheers,
Antoine.

**Comment by grlee77** [comment]
Hi @AntoineD,

I am not familiar with that format, but most likely it could be added. Does VTK ship with its own version of XDMF and do you know the CMAKE flag is used enable it? I don't see a conda package for XDMF itself, so if it is not available via VTK then that would have to be done first.

Assuming VTK provides a copy of XDMF, it should just be a matter of adding the necessary flag to the build scripts linked below (and maybe an import test in the `meta.yaml`):
https://github.com/conda-forge/vtk-feedstock/blob/master/recipe/build.sh
https://github.com/conda-forge/vtk-feedstock/blob/master/recipe/bld.bat

**Comment by AntoineD** [comment]
Hi @grlee77,
yes VTK ships XDMF, the flag to enable it is `-DModule_vtkxdmf2:BOOL=ON`.

**Comment by isuruf** [comment]
@grlee77, can you cancel the tests on outdated commits on your fork? (Builds on forked repos share the queue with conda-forge)

**Comment by grlee77** [comment]
Thanks for the heads up  @isuruf. I did not realize I was even running the CI On that branch.  I went ahead and cancelled all of the pending jobs.

@AntoineD, building with `-DModule_vtkxdmf2:BOOL=ON` worked on OS X when I tested locally, but I didn't try to actually use XDMF.  All I checked was that it created a corresponding `libvtkxdmf2-8.1.1.dylib` and `libvtkxdmf2-8.1.dylib` in the library directory of the conda environment. Is there a Python import related to XDMF that we could test or does that flag only enable it for C++ use?

**Comment by AntoineD** [comment]
Hi @grlee77,

you are right, I finally succeeded to build a working package with `-DModule_vtkIOXdmf2:INTERNAL=ON`.
After failing to build from the vanilla conda-forge's recipe, I was able to build the package from the default repo (with some effort though).
Here is the [PR](https://github.com/AnacondaRecipes/vtk-feedstock/pull/3) .

**Comment by banesullivan** [comment]
Can this be re-opened? #127 dropped xdmf support.

**Comment by grlee77** [comment]
@banesullivan. I have reopened it. I don't recall if dropping it from the 9.0 build was intentional due to problems with the build or an oversight. I suppose adding the changes from #96 back onto current master would allow trying it out

**Comment by banesullivan** [comment]
Thanks for the quick response/action! I've been having trouble building VTK9 locally with xdmf enabled so I'd assume it was dropped due to build problems (and the flags changing)
