### ISSUE TITLE
OpenGL display modules not available on linux 64bit

### ISSUE THREAD

**Issue by gdevenyi** [conda-forge/vtk-feedstock#7]
Trying to build a package against vtk-7.0.0 from conda-forge:

```
 CMake Error at /opt/quarantine/anaconda/4.1.1/build/lib/cmake/vtk-7.0/vtkModuleAPI.cmake:120 (message):
   Requested modules not available:

     vtkRenderingOpenGL2
     vtkRenderingVolumeOpenGL2
 Call Stack (most recent call first):
   /opt/quarantine/anaconda/4.1.1/build/lib/cmake/vtk-7.0/VTKConfig.cmake:88 (vtk_module_config)
   CMakeLists.txt:8 (find_package)
```

**Comment by grlee77** [comment]
I believe the following CMAKE flag is the culprit:
`-DVTK_RENDERING_BACKEND=OpenGL`

VTK 7.0 changed to a new OpenGL2 backend by default, but it looks like the conda-forge build here has specified the older OPENGL backend.  I am not sure if that was an oversight or intentional.  @Korijn?

**Comment by Korijn** [comment]
That was intentional, as suggested by one of the VTK devs. The idea was that more people would be able to run on the old backend than on the new one.

**Comment by grlee77** [comment]
I also ran into a possibly related problem while trying to package mayavi:
conda-forge/staged-recipes#1581

Is there perhaps there a way to provide packages for both options (e.g. via a separate vtk-opengl2 package?)

**Comment by gdevenyi** [comment]
There's a way via build features in conda to have an alternate version http://conda.pydata.org/docs/building/meta-yaml.html#id1

**Comment by Korijn** [comment]
Feel free to open a PR, or explain your proposed solution in more detail so someone else can pick it up.

I recently chimed in at https://github.com/conda/conda/issues/3299 to mention our use case.

**Comment by dfroger** [comment]
Maybe the [libglu](https://github.com/conda-forge/staged-recipes/pull/1966) conda package can be used here?
