### ISSUE TITLE
vtk-7.0.0 hard codes system library paths in it's CMAKE config

### ISSUE THREAD

**Issue by gdevenyi** [conda-forge/vtk-feedstock#8]
I've been running into this error trying to build against vtk:

```
No rule to make target `/usr/lib64/librt.so', needed by `travel_depth/TravelDepthMain'.  Stop.
```

I thoroughly examined the very simple VTK cmake I'm using, and I've come down to it being included somewhere else:

Grepping through the cmake files included with vtk-7.0.0:

``` sh
> grep -r librt
Modules/vtkhdf5.cmake:set(vtkhdf5_LIBRARIES "/opt/quarantine/anaconda/4.1.1/build/lib/libhdf5.so;/usr/lib64/librt.so;/opt/quarantine/anaconda/4.1.1/build/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/opt/quarantine/anaconda/4.1.1/build/lib/libhdf5_hl.so;/opt/quarantine/anaconda/4.1.1/build/lib/libhdf5.so;/usr/lib64/librt.so;/opt/quarantine/anaconda/4.1.1/build/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so")
VTKTargets.cmake:  INTERFACE_LINK_LIBRARIES "/opt/quarantine/anaconda/4.1.1/build/lib/libhdf5.so;/usr/lib64/librt.so;/opt/quarantine/anaconda/4.1.1/build/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/opt/quarantine/anaconda/4.1.1/build/lib/libhdf5_hl.so;/opt/quarantine/anaconda/4.1.1/build/lib/libhdf5.so;/usr/lib64/librt.so;/opt/quarantine/anaconda/4.1.1/build/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;m"
```

It looks like somehow the conda build system's library paths got embedded as target link libraries for CMAKE, so when I try and use it, it also targets those. I don't have my libraries at that location.

**Comment by Korijn** [comment]
Not sure about this; @jakirkham?

**Comment by gdevenyi** [comment]
Confirmed that if I build my own VTK-7.0 from scratch I don't have this issue.

**Comment by patricksnape** [comment]
Grim - looks like the cmake file is hardcoding the paths to all 'linkable' libraries and this includes system libraries such as librt that exist in `/usr/lib64` on CentOS but in other places on Debian for example. I don't see why these libraries couldn't just be relative link requirements? Can you try rebuilding but changing `/usr/lib64/librt.so` to `rt` to see if CMake will just resolve the link requirements itself? If it does, then we can just `sed` those out in our build (I think).

**Comment by Korijn** [comment]
Should we file an issue with VTK maybe? Or is there already a CMAKE option to use relative paths perhaps?

**Comment by patricksnape** [comment]
Maybe try using `CMAKE_SKIP_RPATH`?

**Comment by dfroger** [comment]
I had a similar [problem](https://groups.google.com/a/continuum.io/forum/#!topic/conda/Lb_Vnz6O85s) with ITK some times ago (but didn't found the solution...)

**Comment by grlee77** [comment]
> Can you try rebuilding but changing /usr/lib64/librt.so to rt to see if CMake will just resolve the link requirements itself? 

I encountered this problem for ITK rather than VTK, but can confirm that manually editing the file to makes these changes as suggested above allowed me to build a third party project successfully.  I have raised a related issue in the ITK feedstock here:
https://github.com/conda-forge/itk-feedstock/issues/7

For VTK, there appear to be two files with hardcoded paths that should be removed:
- lib/cmake/vtk-7.1/VTKTargets.cmake
- lib/cmake/vtk-7.1/Modules/vtkhdf5.cmake

**Comment by Korijn** [comment]
Closing this unless someone issues a plan of approach to resolve this.

**Comment by ihnorton** [comment]
Analysis/suggested fix in https://github.com/conda-forge/itk-feedstock/issues/7
PR to fix in ITK: https://github.com/InsightSoftwareConsortium/ITK/pull/343

**Comment by grlee77** [comment]
I think @ihnorton meant to link here: https://github.com/conda-forge/libitk-feedstock/issues/7

**Comment by ManifoldFR** [comment]
This also affects `libXext.so`. On my Ubuntu 19.10 the CMake build links to `/usr/lib64/libXext.so` which does not exist. I circumvented it with a symlink
