### ISSUE TITLE
vtk and Qt support ?

### ISSUE THREAD

**Issue by hadim** [conda-forge/vtk-feedstock#9]
I guess the option needs to be enable during the build. Qt4 is available in conda forge and Qt5 should be also available soon.

```
-DVTK_QT_VERSION:STRING=5 \
-DVTK_Group_Qt:BOOL=ON \
```

See here for Qt5 progress https://github.com/conda-forge/qt-feedstock/issues/5

**Comment by ccordoba12** [comment]
The problem is that this is not an optional dependency, i.e. if you compile VTK with Qt then Qt becomes a runtime, hard dependency of VTK.

**Comment by Korijn** [comment]
A very common misunderstanding though, as I'm starting to experience. :)

**Comment by hadim** [comment]
Sorry @ccordoba12 I am not sure to understand. Does that mean by enabling Qt during the build, Qt MUST be present during runtime ?

In this case we could build an alternative version of vtk having Qt support ?  http://conda.pydata.org/docs/building/meta-yaml.html#features

**Comment by hadim** [comment]
Note that I was able to use `from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor as vtk_renderer` with the vtk version in conda forge... so I guess I have everything I need here.

Should I close ?

**Comment by Korijn** [comment]
That does sound like a valid workaround.

@jakirkham @ocefpaf the need for a policy on alternative builds (optional deps) is a recurring topic... :)

**Comment by jakirkham** [comment]
Had opened this issue ( https://github.com/conda/conda/issues/3299 ) awhile back. Not much we can do until it is solved in `conda`/`conda-build`.

**Comment by ccordoba12** [comment]
There's are some discussions on how to address this: https://github.com/conda/conda-build/issues/1338
